libsepol: silence clang's -Wconditional-uninitialized
When building with -Wconditional-uninitialized, clang reports the
following warning:

    kernel_to_cil.c:1622:37: error: variable 'low_bit' may be
    uninitialized when used here [-Werror,-Wconditional-uninitialized]
                                    low_value = xperms->driver<<8 | low_bit;
                                                                    ^~~~~~~
    kernel_to_cil.c:1587:18: note: initialize the variable 'low_bit' to
    silence this warning
            uint16_t low_bit;
                            ^
                             = 0

This is a false positive because when in_range is true, low_bit is
always initialized when it is used. The warning is nevertheless quite
noisy, so silence it in order to get warnings when a real bug occurs.

Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>